# Generated by Django 3.0.2 on 2020-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200204_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Writ your query', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
