# Generated by Django 3.0.2 on 2020-02-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200204_1038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Query',
        ),
    ]
